# Generated by Django 3.2.9 on 2021-11-02 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='purchase_id',
        ),
    ]
